Adding SECURITY.md file
google/.github pull request #48
Opened 2021-07-29 20:27 UTC by gauntface

2021-08-02 16:03 UTC, annabellegoth2boss requested changes

2021-08-02 16:03 UTC, annabellegoth2boss commented on SECURITY.md
> +To report a security issue, please use http://g.co/vulnz. We use
Change to http**s** on lines 1 and 2

2021-08-02 17:44 UTC, annabellegoth2boss approved these changes

2021-08-02 17:45 UTC, merged

2021-09-16 03:04 UTC, 1Elle1111 commented
Merged

2021-09-16 03:04 UTC, 1Elle1111 commented on SECURITY.md
> +To report a security issue, please use http://g.co/vulnz. We use
Hi

2021-09-16 04:05 UTC, 1Elle1111 reviewed
Hi